---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-aws-secrets
  namespace: production
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: image-dev-app-vars
        objectType: secretsmanager
        jmesPath:
            - path: AWS_ACCESS_KEY_ID
              objectAlias: AWS_ACCESS_KEY_ID
            - path: AWS_BUCKET_NAME
              objectAlias: AWS_BUCKET_NAME
            - path: AWS_REGION
              objectAlias: AWS_REGION
            - path: AWS_SECRET_ACCESS_KEY
              objectAlias: AWS_SECRET_ACCESS_KEY
            - path: COLLECTION_ID
              objectAlias: COLLECTION_ID
            - path: DB_HOST
              objectAlias: DB_HOST
            - path: MYSQL_USER
              objectAlias: MYSQL_USER
            - path: MYSQL_DB
              objectAlias: MYSQL_DB
            - path: MYSQL_PASSWORD
              objectAlias: MYSQL_PASSWORD
            - path: MYSQL_ROOT_PASSWORD
              objectAlias: MYSQL_ROOT_PASSWORD
            - path: JWT_ALGORITHM
              objectAlias: JWT_ALGORITHM
            - path: JWT_SECRET_KEY
              objectAlias: JWT_SECRET_KEY
            - path: PORT
              objectAlias: PORT
            - path: SMTP_API_KEY
              objectAlias: SMTP_API_KEY
            - path: SMTP_FROM_EMAIL
              objectAlias: SMTP_FROM_EMAIL
            - path: SMTP_PASSWORD
              objectAlias: SMTP_PASSWORD
            - path: SMTP_PORT
              objectAlias: SMTP_PORT
            - path: SMTP_SERVER
              objectAlias: SMTP_SERVER
            - path: UPLOAD_DIR
              objectAlias: UPLOAD_DIR


  secretObjects:
    - secretName: myapp-k8s-secret
      type: Opaque
      data:
        - objectName: AWS_ACCESS_KEY_ID
          key: AWS_ACCESS_KEY_ID
        - objectName: AWS_BUCKET_NAME
          key: AWS_BUCKET_NAME
        - objectName: AWS_REGION
          key: AWS_REGION
        - objectName: AWS_SECRET_ACCESS_KEY
          key: AWS_SECRET_ACCESS_KEY
        - objectName: COLLECTION_ID
          key: COLLECTION_ID
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: MYSQL_USER
          key: MYSQL_USER
        - objectName: MYSQL_DB
          key: MYSQL_DB
        - objectName: MYSQL_PASSWORD
          key: MYSQL_PASSWORD
        - objectName: MYSQL_ROOT_PASSWORD
          key: MYSQL_ROOT_PASSWORD
        - objectName: JWT_ALGORITHM
          key: JWT_ALGORITHM
        - objectName: JWT_SECRET_KEY
          key: JWT_SECRET_KEY
        - objectName: PORT
          key: PORT
        - objectName: SMTP_API_KEY
          key: SMTP_API_KEY
        - objectName: SMTP_FROM_EMAIL
          key: SMTP_FROM_EMAIL
        - objectName: SMTP_PASSWORD
          key: SMTP_PASSWORD
        - objectName: SMTP_PORT
          key: SMTP_PORT
        - objectName: SMTP_SERVER
          key: SMTP_SERVER
        - objectName: UPLOAD_DIR
          key: UPLOAD_DIR